language: go
go:
  - 1.x
env:
  - GO111MODULE=on
before_install:
  - go get golang.org/x/lint/golint
before_script:
  - go get -d ./...
script:
  - go build ./...
  - golint ./...
  - go vet ./...
  - go test -v ./...
